name: aibridge
description: Open Source AI API Platform
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+10

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: 2.0.18
  flutter_phoenix: ^1.1.1
  provider: ^6.0.5
  intl: ^0.18.0
  url_launcher: ^6.1.10 # add some lines in Manifest. see info : https://pub.dev/packages/url_launcher#android
  fluttertoast: 8.2.2
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7
  sqflite: ^2.2.6
  path_provider: ^2.0.14 # used for temp directory
  flutter_image_compress: ^1.1.3
  image_picker: 0.8.7
  photo_view: 0.14.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_markdown: ^0.6.17+2
  dio: ^5.4.0
  http: ^1.1.0
  tiktoken: ^1.0.3
  dart_openai: ^4.0.0
  flutter_colorpicker: ^1.0.3
  rename: ^3.0.1
  flutter_native_splash: ^2.3.7
  package_info_plus: ^4.1.0 # internet permission required
  native_exif: ^0.5.0
  path: ^1.8.3
  image_gallery_saver: ^2.0.3
  png_chunks_encode: ^1.0.0
  png_chunks_extract: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: MouldyCheeseRegular
      fonts:
        - asset: fonts/MouldyCheeseRegular.ttf
    - family: MotleyForcesRegular
      fonts:
        - asset: fonts/MotleyForcesRegular.ttf

flutter_intl:
  enabled: true

flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher_icon_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/launcher_icon_512.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter_native_splash: #flutter pub run flutter_native_splash:create
  color: "#000000"
  fullscreen: true
  image: images/launcher_icon_1024.png
  android: true
  android_12:
    image: images/launcher_icon_1024.png
  ios: true

# To rename project
# install rename package
# install rename CLI tool via `flutter pub global activate rename`
# set app name with
# rename setAppName --targets ios,android --value "YourAppName"

# To change package name for android
# flutter pub run change_app_package_name:main com.new.package.name

